/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ZimmerRouteImport } from './routes/zimmer'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ReservationsRouteImport } from './routes/reservations'
import { Route as PlansDemoRouteImport } from './routes/plans-demo'
import { Route as ImpressumRouteImport } from './routes/impressum'
import { Route as GalerieRouteImport } from './routes/galerie'
import { Route as DatenschutzRouteImport } from './routes/datenschutz'
import { Route as AgbRouteImport } from './routes/agb'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as ApiResendInboundRouteImport } from './routes/api/resend-inbound'
import { Route as ApiCalendarDoticsRouteImport } from './routes/api/calendar[.]ics'
import { Route as AdminLoginRouteImport } from './routes/admin.login'

const ZimmerRoute = ZimmerRouteImport.update({
  id: '/zimmer',
  path: '/zimmer',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ReservationsRoute = ReservationsRouteImport.update({
  id: '/reservations',
  path: '/reservations',
  getParentRoute: () => rootRouteImport,
} as any)
const PlansDemoRoute = PlansDemoRouteImport.update({
  id: '/plans-demo',
  path: '/plans-demo',
  getParentRoute: () => rootRouteImport,
} as any)
const ImpressumRoute = ImpressumRouteImport.update({
  id: '/impressum',
  path: '/impressum',
  getParentRoute: () => rootRouteImport,
} as any)
const GalerieRoute = GalerieRouteImport.update({
  id: '/galerie',
  path: '/galerie',
  getParentRoute: () => rootRouteImport,
} as any)
const DatenschutzRoute = DatenschutzRouteImport.update({
  id: '/datenschutz',
  path: '/datenschutz',
  getParentRoute: () => rootRouteImport,
} as any)
const AgbRoute = AgbRouteImport.update({
  id: '/agb',
  path: '/agb',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const ApiResendInboundRoute = ApiResendInboundRouteImport.update({
  id: '/api/resend-inbound',
  path: '/api/resend-inbound',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCalendarDoticsRoute = ApiCalendarDoticsRouteImport.update({
  id: '/api/calendar.ics',
  path: '/api/calendar.ics',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/agb': typeof AgbRoute
  '/datenschutz': typeof DatenschutzRoute
  '/galerie': typeof GalerieRoute
  '/impressum': typeof ImpressumRoute
  '/plans-demo': typeof PlansDemoRoute
  '/reservations': typeof ReservationsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/zimmer': typeof ZimmerRoute
  '/admin/login': typeof AdminLoginRoute
  '/api/calendar.ics': typeof ApiCalendarDoticsRoute
  '/api/resend-inbound': typeof ApiResendInboundRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agb': typeof AgbRoute
  '/datenschutz': typeof DatenschutzRoute
  '/galerie': typeof GalerieRoute
  '/impressum': typeof ImpressumRoute
  '/plans-demo': typeof PlansDemoRoute
  '/reservations': typeof ReservationsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/zimmer': typeof ZimmerRoute
  '/admin/login': typeof AdminLoginRoute
  '/api/calendar.ics': typeof ApiCalendarDoticsRoute
  '/api/resend-inbound': typeof ApiResendInboundRoute
  '/admin': typeof AdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/agb': typeof AgbRoute
  '/datenschutz': typeof DatenschutzRoute
  '/galerie': typeof GalerieRoute
  '/impressum': typeof ImpressumRoute
  '/plans-demo': typeof PlansDemoRoute
  '/reservations': typeof ReservationsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/zimmer': typeof ZimmerRoute
  '/admin/login': typeof AdminLoginRoute
  '/api/calendar.ics': typeof ApiCalendarDoticsRoute
  '/api/resend-inbound': typeof ApiResendInboundRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/agb'
    | '/datenschutz'
    | '/galerie'
    | '/impressum'
    | '/plans-demo'
    | '/reservations'
    | '/sitemap.xml'
    | '/zimmer'
    | '/admin/login'
    | '/api/calendar.ics'
    | '/api/resend-inbound'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/agb'
    | '/datenschutz'
    | '/galerie'
    | '/impressum'
    | '/plans-demo'
    | '/reservations'
    | '/sitemap.xml'
    | '/zimmer'
    | '/admin/login'
    | '/api/calendar.ics'
    | '/api/resend-inbound'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/agb'
    | '/datenschutz'
    | '/galerie'
    | '/impressum'
    | '/plans-demo'
    | '/reservations'
    | '/sitemap.xml'
    | '/zimmer'
    | '/admin/login'
    | '/api/calendar.ics'
    | '/api/resend-inbound'
    | '/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AgbRoute: typeof AgbRoute
  DatenschutzRoute: typeof DatenschutzRoute
  GalerieRoute: typeof GalerieRoute
  ImpressumRoute: typeof ImpressumRoute
  PlansDemoRoute: typeof PlansDemoRoute
  ReservationsRoute: typeof ReservationsRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ZimmerRoute: typeof ZimmerRoute
  ApiCalendarDoticsRoute: typeof ApiCalendarDoticsRoute
  ApiResendInboundRoute: typeof ApiResendInboundRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/zimmer': {
      id: '/zimmer'
      path: '/zimmer'
      fullPath: '/zimmer'
      preLoaderRoute: typeof ZimmerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reservations': {
      id: '/reservations'
      path: '/reservations'
      fullPath: '/reservations'
      preLoaderRoute: typeof ReservationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plans-demo': {
      id: '/plans-demo'
      path: '/plans-demo'
      fullPath: '/plans-demo'
      preLoaderRoute: typeof PlansDemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/impressum': {
      id: '/impressum'
      path: '/impressum'
      fullPath: '/impressum'
      preLoaderRoute: typeof ImpressumRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/galerie': {
      id: '/galerie'
      path: '/galerie'
      fullPath: '/galerie'
      preLoaderRoute: typeof GalerieRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/datenschutz': {
      id: '/datenschutz'
      path: '/datenschutz'
      fullPath: '/datenschutz'
      preLoaderRoute: typeof DatenschutzRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agb': {
      id: '/agb'
      path: '/agb'
      fullPath: '/agb'
      preLoaderRoute: typeof AgbRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/api/resend-inbound': {
      id: '/api/resend-inbound'
      path: '/api/resend-inbound'
      fullPath: '/api/resend-inbound'
      preLoaderRoute: typeof ApiResendInboundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/calendar.ics': {
      id: '/api/calendar.ics'
      path: '/api/calendar.ics'
      fullPath: '/api/calendar.ics'
      preLoaderRoute: typeof ApiCalendarDoticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminLoginRoute: typeof AdminLoginRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminLoginRoute: AdminLoginRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AgbRoute: AgbRoute,
  DatenschutzRoute: DatenschutzRoute,
  GalerieRoute: GalerieRoute,
  ImpressumRoute: ImpressumRoute,
  PlansDemoRoute: PlansDemoRoute,
  ReservationsRoute: ReservationsRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ZimmerRoute: ZimmerRoute,
  ApiCalendarDoticsRoute: ApiCalendarDoticsRoute,
  ApiResendInboundRoute: ApiResendInboundRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
